export enum EnumRole {
  ANALYST = "ANALYST",
  CLIENT = "CLIENT",
  ADMIN = "ADMIN",
}

export enum EnumSector {
  MANUTENCAO_TI = "MANUTENCAO_TI",
  MANUTENCAO_ELETRICA = "MANUTENCAO_ELETRICA",
  MANUTENCAO_PREDIAL = "MANUTENCAO_PREDIAL",
  OUTROS = "MANUTENCAO_PREDIAL",
}
